### PR TITLE
Added possibility to add rootkey for objects

### PR DESCRIPTION
**Pull request by nicolaspierre1990**
Hello,

I have added the possibilty to add rootkey to the object.

Because netcore3.1 is out of LTS support I have updated the test project to NET6 and the main project to netstandard2.1

Updated version to 1.1.0 for breaking changes

### CODE REVIEW

**Comment by lawrence-laz** [comment]
Hi,

Thanks for the PR! I'll make sure to look through it a bit later.

Just a couple of things right off the bat:

1.  I'd like to follow the [semantic versioning](https://semver.org/) where a breaking change triggers a major bump, so this would be `2.0.0`. I should probably update the readme regarding the use of semantic versioning 😀
2. If possible, I'd like to avoid making breaking changes by:
    - Sticking the the library to `netstandard2.0` for compatibility with .net framework (some unfortunate people still have to use it, including me). NET6 bump is fine.
    - Creating an overload of the method (and constructor) instead of modifying the existing one, not to break ABI and to avoid using default parameters (they can be confusing especially in package code)

Let me know if that's possible with what you are trying to do

**Comment by lawrence-laz** [comment]
All looks good, except for the couple things mentioned above and the pipeline needs updating

We can address those here, or I can fix them up after merging this PR. Whichever you prefer?

**Comment by nicolaspierre1990** [comment]
I'll take a look at them later today

**Comment by nicolaspierre1990** [comment]
@lawrence-laz I have addressed your comments

**Comment by nicolaspierre1990** [comment]
Will you push this to nuget ?

**Comment by lawrence-laz** [comment]
> Will you push this to nuget ?

I wanted to make some unrelated changes as well. I'll try to get it done during my lunch break today.

**Comment by lawrence-laz** [comment]
The nuget is now pushed as `1.1.0`, it will take a bit for it to pass validation but it should be listed publicly after an hour or so.

**Pull request merged**
